// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW1WYamli6t8ckMh8KaYGwqF_rux7hEeA',
    appId: '1:144251091322:web:5d86f3b7ae18b3332c3ec3',
    messagingSenderId: '144251091322',
    projectId: 'agrarian-8487f',
    authDomain: 'agrarian-8487f.firebaseapp.com',
    storageBucket: 'agrarian-8487f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcU8ldQ9xLXnMAGqDspoM4iGBbWHEqDVI',
    appId: '1:144251091322:android:97723fcf57a2c7532c3ec3',
    messagingSenderId: '144251091322',
    projectId: 'agrarian-8487f',
    storageBucket: 'agrarian-8487f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCYvSclXHTq_e-1wdBzhx7YaCdtTW9gQ',
    appId: '1:144251091322:ios:07a9cd9b7a2f36272c3ec3',
    messagingSenderId: '144251091322',
    projectId: 'agrarian-8487f',
    storageBucket: 'agrarian-8487f.firebasestorage.app',
    iosBundleId: 'com.example.agrarian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCYvSclXHTq_e-1wdBzhx7YaCdtTW9gQ',
    appId: '1:144251091322:ios:07a9cd9b7a2f36272c3ec3',
    messagingSenderId: '144251091322',
    projectId: 'agrarian-8487f',
    storageBucket: 'agrarian-8487f.firebasestorage.app',
    iosBundleId: 'com.example.agrarian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW1WYamli6t8ckMh8KaYGwqF_rux7hEeA',
    appId: '1:144251091322:web:276ad177f18480792c3ec3',
    messagingSenderId: '144251091322',
    projectId: 'agrarian-8487f',
    authDomain: 'agrarian-8487f.firebaseapp.com',
    storageBucket: 'agrarian-8487f.firebasestorage.app',
  );
}
